# Generated by Django 5.2.4 on 2025-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
                ('condemning_dia', models.CharField(max_length=100)),
                ('last_shop_issue_size', models.CharField(max_length=100)),
                ('tread_diameter_new', models.CharField(max_length=100)),
                ('wheel_gauge', models.CharField(max_length=100)),
            ],
        ),
    ]
