# Generated by Django 5.2.4 on 2025-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelspecification',
            name='form_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
